### ISSUE TITLE
[iOS] Barcode bounding box right position is wrong

### ISSUE THREAD

**Issue by zzz08900** [gev2002/react-native-vision-camera-barcodes-scanner#2]
Ok I'm playing around this plugin in last few days and noticed the bounding box does not look right so I double checked the calculation codes and found a minor mistake.
Also I figure having displayValue of barcodes returned to JS side would be great.

A pull request is already there. Haven't checked Android side yet so that one is only for iOS.

**Comment by zzz08900** [comment]
Great work btw. Finally we have a replacement for [rodgomesc](https://github.com/rodgomesc/vision-camera-code-scanner)'s old and faithful [vision-camera-code-scanner](https://github.com/rodgomesc/vision-camera-code-scanner)

**Comment by zzz08900** [comment]
Just updated the PR to include displayValue on Android as well so both platforms retain the same return value format.

**Comment by gev2002** [comment]
Hello, thanks for your work. I wrote this plugin so quickly that I didn’t notice that I wrote y instead of x.
